# This is a basic workflow to help you get started with Actions

name: Assemble Debug

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Rename google-services.json file
        run: |
          mv app/google-services-github.json app/google-services.json
  
      - name: Rename keystore.properties file
        run: |
          mv keystore-github.properties keystore.properties
          
      - name: Rename tvhclient.properties file
        run: |
          mv tvhclient-github.properties tvhclient.properties
          
      # Step: Replace stuff in google services json file
      - uses: jwsi/secret-parser@v1
        with:
          filename: app/google-services.json
          secret-name: PROJECT_NUMBER
          secret-value: ${{ secrets.PROJECT_NUMBER }}

      - uses: jwsi/secret-parser@v1
        with:
          filename: app/google-services.json
          secret-name: MOBILE_SDK_APP_ID
          secret-value: ${{ secrets.MOBILE_SDK_APP_ID }}

      - uses: jwsi/secret-parser@v1
        with:
          filename: app/google-services.json
          secret-name: OAUTH_CLIENT_ID
          secret-value: ${{ secrets.OAUTH_CLIENT_ID }}

      - uses: jwsi/secret-parser@v1
        with:
          filename: app/google-services.json
          secret-name: API_KEY
          secret-value: ${{ secrets.API_KEY }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      # Step: Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug
      
